- name: Deploy
  hosts: all
  tasks:
    - name: Git tag
      ansible.builtin.shell: |
        git tag {{ semaphore_vars.task_details.incoming_version }} -f
    # - name: Git push
    #   ansible.builtin.shell: |
    #     git push --tags
    - name: Deploy
      ansible.builtin.debug:
        msg: "version {{ semaphore_vars.task_details.incoming_version }} 배포 완료"
