- name: Test pip
  hosts: all
  tasks:
    - name: Git repo
      ansible.builtin.shell: |
        git remote get-url --push origin
      register: git_repo_url
    - name: Git diff
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: /tmp/repo
        clone: false
        update: false
      check: true
      diff: true
